spring.datasource.url=jdbc:mysql://mydb.cux4wyao4uq3.us-east-1.rds.amazonaws.com:3306/feedback_db
spring.datasource.username=root
spring.datasource.password=Iswarya123
app.jwt.secret=bXlTZWNyZXRLZXkxMjM0NTZteVNlY3JldEtleTEyMzQ1Ng==
app.jwt.expiration-ms=86400000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8081